menu: #配置页头显示那些菜单
#  Home: /
  Archives: /archives
  #Reading: /reading
  About: /about
# Guestbook: /about
#rss: /atom.xml

excerpt_link: Read More #摘要链接文字
archive_yearly: false #按年存档

widgets: #配置页脚显示哪些小挂件
  - category
  # - tag
  - tagcloud
  - recent_posts
  # - blogroll

blogrolls: #友情链接
  - funny99's taobao shop: https://funny99.taobao.com/
  - funny99's friend website: http://www.muoun.com

archive_date_format: MMM DD
fancybox: true #是否开启fancybox效果

duoshuo_shortname: funny99 #多说账号

google_analytics:
favicon: /favicon.ico

baidu_tongji: true #统计
